# Generated by Django 4.2.25 on 2025-11-09 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'managed': True},
        ),
    ]
