# Generated by Django 4.2.25 on 2025-11-09 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_producto_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='idCategoria',
            field=models.ForeignKey(db_column='idCategoria', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoria'),
        ),
        migrations.AddField(
            model_name='producto',
            name='idSubcategoria',
            field=models.ForeignKey(db_column='idSubcategoria', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subcategoria'),
        ),
    ]
