# Generated by Django 4.2.25 on 2025-11-13 08:28
# Modified to skip table creation as all tables already exist in database

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_fix_duplicate_columns'),
    ]

    operations = [
        # All models already exist in database - no operations needed
    ]
