# Generated by Django 4.2.25 on 2025-11-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_producto_idcategoria_producto_idsubcategoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('direccion', models.CharField(max_length=30, null=True)),
                ('telefono', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Distribuidor',
            fields=[
                ('idDistribuidor', models.AutoField(primary_key=True, serialize=False)),
                ('nombreDistribuidor', models.CharField(max_length=30, null=True)),
                ('contacto', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'distribuidores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DistribuidorProducto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idDistribuidor', models.IntegerField()),
                ('idProducto', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'distribuidor_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Repartidor',
            fields=[
                ('idRepartidor', models.AutoField(primary_key=True, serialize=False)),
                ('nombreRepartidor', models.CharField(max_length=50, null=True)),
                ('telefono', models.CharField(max_length=11, null=True)),
                ('estado_turno', models.CharField(default='Disponible', max_length=20, null=True)),
            ],
            options={
                'db_table': 'repartidores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('id_rol', models.IntegerField()),
                ('idCliente', models.IntegerField(null=True)),
                ('fechaCreacion', models.DateTimeField()),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('telefono', models.CharField(max_length=20, null=True)),
                ('direccion', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MensajeContacto',
            fields=[
                ('idMensaje', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mensajes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('idNotificacion', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'notificaciones',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('idProfile', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.IntegerField()),
                ('imagen', models.CharField(max_length=255, null=True)),
                ('descripcion', models.TextField(null=True)),
            ],
            options={
                'db_table': 'perfil',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'managed': False},
        ),
    ]
