# Generated by Django 4.2.25 on 2025-11-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_fix_duplicate_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repartidor',
            fields=[
                ('idRepartidor', models.AutoField(primary_key=True, serialize=False)),
                ('nombreRepartidor', models.CharField(max_length=100, db_column='nomberepartidor')),
                ('telefonoRepartidor', models.CharField(max_length=20, db_column='telefonoRepartidor')),
                ('email', models.EmailField(blank=True, db_column='email', max_length=100, null=True)),
            ],
            options={
                'db_table': 'repartidores',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Distribuidor',
            fields=[
                ('idDistribuidor', models.AutoField(primary_key=True, serialize=False)),
                ('nombreDistribuidor', models.CharField(max_length=30, null=True, db_column='nombredistribuidor')),
                ('contacto', models.CharField(max_length=20, db_column='contacto')),
            ],
            options={
                'db_table': 'distribuidores',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DistribuidorProducto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idDistribuidor', models.IntegerField(db_column='iddistribuidor')),
                ('idProducto', models.CharField(max_length=30, db_column='idproducto')),
            ],
            options={
                'db_table': 'distribuidor_producto',
                'managed': True,
            },
        ),
    ]
