# Generated by Django 4.2.25 on 2025-11-13 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cliente_distribuidor_distribuidorproducto_repartidor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'managed': True},
        ),
    ]
