# Generated by Django 4.2.25 on 2025-11-13 08:56
# Modified - column already exists in database

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_categoria_options'),
    ]

    operations = [
        # Column already exists - no operations needed
    ]
