# Generated by Django 4.2.25 on 2025-11-13 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_categoria_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoProducto',
            fields=[
                ('idMovimiento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA_INICIAL', 'Entrada Inicial'), ('AJUSTE_MANUAL_ENTRADA', 'Ajuste Manual (Entrada)'), ('AJUSTE_MANUAL_SALIDA', 'Ajuste Manual (Salida)'), ('SALIDA_VENTA', 'Salida por Venta')], max_length=50)),
                ('cantidad', models.IntegerField()),
                ('stock_anterior', models.IntegerField()),
                ('stock_nuevo', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('id_pedido', models.ForeignKey(blank=True, db_column='idPedido', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='core.producto')),
            ],
            options={
                'db_table': 'movimientos_producto',
                'ordering': ['-fecha'],
            },
        ),
    ]
