# Generated by Django 4.2.25 on 2025-11-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_movimientoproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoproducto',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
