# Generated by Django 4.2.25 on 2025-11-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_movimientoproducto_precio_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoproducto',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo por unidad para movimientos de entrada.', max_digits=10),
        ),
    ]
