# Generated by Django 4.2.25 on 2025-11-21 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_movimientoproducto_costo_unitario'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionProblema',
            fields=[
                ('idNotificacion', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='problemas_entrega/')),
                ('fechaReporte', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
                ('idPedido', models.ForeignKey(db_column='idPedido', on_delete=django.db.models.deletion.CASCADE, to='core.pedido')),
            ],
            options={
                'db_table': 'notificaciones_problema',
                'ordering': ['-fechaReporte'],
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Notificacion',
        ),
    ]
