# Generated by Django 4.2.25 on 2025-11-21 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_notificacionproblema_delete_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacionproblema',
            name='fecha_respuesta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificacionproblema',
            name='respuesta_admin',
            field=models.TextField(blank=True, null=True),
        ),
    ]
