# Generated by Django 4.2.25 on 2025-11-26 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_pedido_facturas_enviadas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='fecha',
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='idPedido',
            field=models.ForeignKey(blank=True, db_column='idPedido', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.pedido'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='idProducto',
            field=models.ForeignKey(blank=True, db_column='idProducto', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.producto'),
        ),
        migrations.AddField(
            model_name='movimientoproducto',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, help_text='Fecha de vencimiento del producto', null=True),
        ),
        migrations.AddField(
            model_name='movimientoproducto',
            name='iva',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor del IVA (19%)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='movimientoproducto',
            name='lote',
            field=models.CharField(blank=True, help_text='Código del lote del producto', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movimientoproducto',
            name='total_con_iva',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total incluyendo IVA', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado_pago',
            field=models.CharField(choices=[('Pago Completo', 'Pago Completo'), ('Pago Parcial', 'Pago Parcial')], default='Pago Completo', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado_pedido',
            field=models.CharField(choices=[('Confirmado', 'Confirmado'), ('En Preparación', 'En Preparación'), ('En Camino', 'En Camino'), ('Entregado', 'Entregado'), ('Completado', 'Completado'), ('Problema en Entrega', 'Problema en Entrega')], default='Confirmado', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='facturas_enviadas',
            field=models.PositiveIntegerField(db_column='facturasEnviadas', default=0),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fechaCreacion',
            field=models.DateTimeField(blank=True, db_column='fechaCreacion', null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, db_column='fechaVencimiento', null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='idCliente',
            field=models.ForeignKey(blank=True, db_column='idCliente', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cliente'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='idRepartidor',
            field=models.ForeignKey(blank=True, db_column='idRepartidor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.repartidor'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='pedidoproducto',
            name='idPedido',
            field=models.ForeignKey(blank=True, db_column='idPedido', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.pedido'),
        ),
        migrations.AddField(
            model_name='pedidoproducto',
            name='idProducto',
            field=models.ForeignKey(blank=True, db_column='idProducto', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.producto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(default='Confirmado', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='pedidoproducto',
            unique_together={('idPedido', 'idProducto')},
        ),
    ]
