# Generated by Django 4.2.25 on 2025-11-26 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_confirmacionentrega'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteProducto',
            fields=[
                ('idLote', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_lote', models.CharField(help_text='Código único del lote', max_length=100)),
                ('fecha_entrada', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('cantidad_inicial', models.IntegerField(help_text='Cantidad inicial del lote')),
                ('cantidad_disponible', models.IntegerField(help_text='Cantidad disponible actual')),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_con_iva', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('iva', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=200, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='core.producto')),
            ],
            options={
                'db_table': 'lotes_producto',
                'ordering': ['fecha_entrada'],
                'unique_together': {('producto', 'codigo_lote')},
            },
        ),
        migrations.CreateModel(
            name='MovimientoLote',
            fields=[
                ('idMovimientoLote', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(help_text='Cantidad tomada de este lote')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='core.loteproducto')),
                ('movimiento_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_lote', to='core.movimientoproducto')),
            ],
            options={
                'db_table': 'movimientos_lote',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='movimientoproducto',
            name='lote_origen',
            field=models.ForeignKey(blank=True, help_text='Lote del cual salió el producto (para movimientos de salida)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.loteproducto'),
        ),
    ]
