# Generated by Django 4.2.25 on 2025-12-10 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_producto_precio_venta'),
    ]

    operations = [
    ]
