# Generated by Django 4.2.25 on 2025-12-13 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_email_column_size'),
        ('core', '0044_create_notificaciones_tables'),
    ]

    operations = [
    ]
